[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.authenticate]
path = 'contracts/authenticate.clar'
clarity_version = 3
epoch = 3.1

[contracts.safe]
path = 'contracts/safe.clar'
clarity_version = 3
epoch = 3.1

[contracts.smart-account]
path = 'contracts/smart-account.clar'
clarity_version = 3
epoch = 3.1

[contracts.uint256-lib]
path = 'contracts/uint256-lib/uint256-lib.clar'
clarity_version = 3
epoch = 3.1

[contracts.webauthn]
path = 'contracts/webauthn.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
