[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.safe]
path = 'contracts/safe.clar'
clarity_version = 3
epoch = 3.1

[contracts.smart-account]
path = 'contracts/smart-account.clar'
clarity_version = 3
epoch = 3.1

[contracts.smart-account-factory]
path = 'contracts/smart-account-factory.clar'
clarity_version = 3
epoch = 3.1

[contracts.uint256-lib]
path = 'contracts/uint256-lib/uint256-lib.clar'
clarity_version = 3
epoch = 3.1

[contracts.passkeysv1]
path = 'contracts/auth/passkeysv1.clar'
clarity_version = 3
epoch = 3.1

[contracts.passkeysv2]
path = 'contracts/auth/passkeysv2.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
